addAssignees: author
numberOfAssignees: 1

addReviewers: true
numberOfReviewers: 1
useReviewGroups: true
reviewGroups:
  devs:    
    - sandrade-dcl    
    - lorux0
    - davidejensen
    - dalkia
    - popuz
    - Kinerius
    - mikhail-dcl
    - pravusjif
  qa:
    - kwssbocian
    - kwsskulinski
    - anicalbano

filterLabels:
  exclude:
    - no_reviewers
    - "Not QA Needed"
    - "No QA Needed"
